import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import ClientNavbar from "@/components/ClientNavbar";
import Theme from "./Theme/theme";
import { WixClientContextProvider } from "@/context/wixContext";
import ReduxProvider from "./redux/ReduxProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <WixClientContextProvider>
            <Theme>
              <ClientNavbar />
              {children}
              <Footer />
            </Theme>
          </WixClientContextProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
